settings:
  name: BlueXP software updates
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
  - title: BlueXP software updates
    url: /index.html
  - section: release-notes
  - section: get-started
  - section: ontap
  - section: support
  - title: Legal notices
    url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family