settings:
  name: BlueXP software updates
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar: 
  entries:
  - title: BlueXP software updates
    url: /index.html
  - title: Release notes
    entries:
      - title: What's new
        url: /whats-new.html
      - title: Known issues
        url: /known-issues.html
  - title: Get started
    entries:
      - title: Learn about ONTAP updates 
        url: /software-updates.html
      - title: Prerequisites
        url: /prerequisites-ontap-update.html
      - title: Quick start
        url: /quick-start-ontap-update.html
      - title: Access BlueXP software updates
        url: /login-software-updates.html
      - title: FAQs
        url: /software-updates-faq.html
  - title: Use BlueXP software updates
    entries:
      - title: Choose ONTAP target version
        url: /choose-ontap-98-later.html
      - title: Fix ONTAP blocker and acknowledge warnings
        url: /fix-blockers-warnings.html
      - title: Complete ONTAP storage system update
        url: /update-storage-system.html
      - title: Validate the status of ONTAP storage system update
        url: /validate-storage-system-update.html
  - title: Knowledge and support
    entries:
      - title: Register for support
        url: /task-support-registration.html
      - title: Get help
        url: /task-get-help.html
  - title: Legal notices
    url: /legal-notices.html