---
sidebar: sidebar
permalink: get-started/prerequisites-ontap-update.html
keywords: prerequisites for ontap update, ontap update requirements, ontap update versions, prepare for ontap update
summary: Review the prerequisites and requirements before proceeding with your ONTAP update.
---
= Prepare to update ONTAP using BlueXP software updates
:icons: font
:imagesdir: ../media/

[.lead]

You should review the prerequisites and requirements before proceeding with your ONTAP update. You can use BlueXP software updates to verify the readiness of your operational environment, login, network access, and web browser.

[NOTE]
=====
*Supported roles:* Organization admin, Folder or project admin, or Storage admin

link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[Learn about BlueXP access roles.]
=====

To use BlueXP software updates, you should ensure that your environment meets all requirements.

* A working environment is set up in BlueXP.
* Administrator credentials are available for the desired cluster while performing software update.
* All the nodes in the cluster are sending AutoSupport data.
* All nodes should be running on ONTAP 9.10 or later versions.
* Nodes should not be in a MetroCluster configuration.