---
sidebar: sidebar
permalink: get-started/prerequisites-ontap-update.html
keywords: prerequisites for ontap update, ontap update requirements, ontap update versions
summary: Review the prerequisites and requirements before proceeding with your ONTAP update.
---
= Prepare to update ONTAP using BlueXP software updates
:icons: font
:imagesdir: ../media/

[.lead]
Get started with BlueXP software updates by verifying the readiness of your operational environment, login, network access, and web browser.

To use BlueXP software updates, you should ensure that your environment meets all requirements.

* A BlueXP organization is available.
* A working environment is set up in BlueXP.
* Administrator privileges are available to perform software update using System Manager.
* Administrator credentials are available for the desired cluster while performing software update. 
* All the nodes in the cluster are sending AutoSupport data.
* All nodes should be running on ONTAP 9.10 or later versions.
* Nodes should not be in a MetroCluster configuration. 