---
sidebar: sidebar
permalink: get-started/software-updates-faq.html
keywords: ontap update faq, ontap update frequently asked questions, software updates faq, software updates frequently asked questions
summary: View the answers to the frequently asked questions about BlueXP software updates.
---
= Frequently asked questions for BlueXP software updates
:icons: font
:imagesdir: ../media/

[.lead]

This FAQ can help if you're just looking for a quick answer to a question.

*What's the BlueXP software updates URL?*

For the URL, in a browser, enter: https://console.bluexp.netapp.com/

*Do you need a license to use BlueXP software updates?*

A NetApp License File (NLF) is not required. 

*Why am I not able to view the cluster in the history tab even after updating the ONTAP version of the cluster?*

 It takes 2 to 3 hours for the cluster to appear in the history tab. Once the ONTAP version of the cluster is updated, an AutoSupport ticket is generated. It takes 2 to 3 hours to process the AutoSupport ticket and reflect the latest version of ONTAP. 

*Why am I seeing the older version of ONTAP in the software updates dashboard even after updating the ONTAP version of the cluster?*

  It takes 2 to 3 hours for the cluster to appear in the history tab. Once the ONTAP version of the cluster is updated, an AutoSupport ticket is generated. It takes 2 to 3 hours to process the AutoSupport ticket and reflect the latest version of ONTAP. 

*Why am I seeing different screens for different updates?*

  This is due to the current ONTAP version and unavailability of Blue XP connector for clusters. A BlueXP connector performs the ONTAP update within Blue XP and you do not need to move out of Blue XP for an update. The following matrix provides the expected experience for ONTAP update.  

|===
    |*Current ONTAP version*  | *Update experience*

    |9.12 and above | All steps of ONTAP update happen within Blue XP.
    |9.10 to 9.12  | Preparation for ONTAP update happens within Blue XP Software updates screens. You will be navigated to System Manager to perform the actual ONTAP update. To execute all steps of ONTAP update within Blue XP, you need to set up a connector. Refer to connector setup process here. 
    |9.8 to 9.10  | Preparation for ONTAP update happens within Blue XP Software updates screens. You will be navigated to System Manager to perform the actual ONTAP update. 
    |Below 9.7 | Automated ONTAP update is not supported for this cluster. You need to update ONTAP manually. For more information, see link:https://docs.netapp.com/us-en/ontap/upgrade/index.html[manually update your storage systems].

|===

*What is cluster discovery?*

To perform ONTAP update for your desired cluster, you need to provide the credentials for connecting to the cluster. As part of cluster discovery, you would be asked to provide admin credentials so that the ONTAP update can be executed automatically. 

 
